/*
Introduction to Data Analytics for Business
by University of Colorado Boulder
*/


#week 3 quiz
/*1. How many aircrafts are there in the PLANES table?*/

SELECT COUNT(*)
FROM PLANES
#25


/*2. Write a query that provides a list of all planes that have a seat count of 100 or more,
 ordered from lowest to highest number of seats.

What is the TAIL_NUMBER of the plane with the second lowest number of seats in that list?*/

SELECT TAIL_NUMBER, SEAT_COUNT
FROM PLANES
WHERE seat_count > 100
ORDER BY seat_count ASC
LIMIT 2
#N120EE      |        124

/*3. Write a query that provides the number of flights flown by each aircraft.

Which aircraft flew the most flights?*/
SELECT COUNT(*)
FROM FLIGHTS
#50 flights

SELECT DISTINCT *
FROM FLIGHTS
#50 flights

SELECT COUNT (DISTINCT TAIL_NUMBER)
FROM FLIGHTS
#22 planes

SELECT SUM(TAIL_NUMBER)
FROM FLIGHTS
GROUP BY TAIL_NUMBER

/*4. 4. 
Write a query that provides a list of planes that flew more than 600 passengers across all flights.

How many planes are in that list?*/
SELECT TAIL_NUMBER
FROM FLIGHTS
GROUP BY TAIL_NUMBER
HAVING SUM(PASSENGER_COUNT) > 600
#3

/*5. 
Write a query that provides the total number of flights by country.

How many flights originated in the United States (Country US)?*/

SELECT DISTINCT COUNTRY
FROM AIRPORTS
ORDER BY COUNTRY DESC

#Implicit JOIN
SELECT *
FROM FLIGHTS, AIRPORTS
WHERE FLIGHTS.DEPARTURE_AIRPORT=AIRPORTS.AIRPORT

#inner join
SELECT *
FROM FLIGHTS
INNER JOIN AIRPORTS
ON FLIGHTS.DEPARTURE_AIRPORT=AIRPORTS.AIRPORT
WHERE AIRPORTS.COUNTRY="US"
#34

SELECT FLIGHTS.FLIGHT_ID, FLIGHTS.DEPARTURE_AIRPORT, AIRPORTS.COUNTRY
FROM FLIGHTS
INNER JOIN AIRPORTS
ON FLIGHTS.DEPARTURE_AIRPORT=AIRPORTS.AIRPORT
WHERE AIRPORTS.COUNTRY="US"


/*6. 
Write a query that provides the total number of flights by regionality.

Which regionality has the second highest number of flights?*/


SELECT COUNT (DISTINCT FLIGHTS.FLIGHT_ID) AS NUM_FLIGHTS, CITY_PAIRS.REGIONALITY
FROM FLIGHTS, CITY_PAIRS
WHERE FLIGHTS.DEPARTURE_AIRPORT=CITY_PAIRS.DEPARTURE_AIRPORT
GROUP BY CITY_PAIRS.REGIONALITY
ORDER BY NUM_FLIGHTS DESC
#US-US

/*7. 
How many CITY_PAIRS are there which depart from one of the following airports?

KLAX, KDEN, KORD, KDET, KLGA

Hint: use the IN operator!*/
SELECT COUNT(*)
FROM CITY_PAIRS
WHERE DEPARTURE_AIRPORT IN ('KLAX','KDEN', 'KORD', 'KDET', 'KLGA')
#722

/*8. 
How many airports are missing elevation values?*/
SELECT COUNT(*)
FROM AIRPORTS
WHERE ELEVATION IS NULL
#6


/*9. 
What flight number had the lowest passenger count (try using a subquery if you can!)?*/
SELECT flight_number, passenger_count
FROM flights
ORDER BY passenger_count ASC
LIMIT 1


/*10. 
What is the average distance flown by SKY Airline flights (nearest mile)?*/


SELECT FLIGHTS.FLIGHT_ID, FLIGHTS.FLIGHT_NUMBER, CITY_PAIRS.DISTANCE
FROM FLIGHTS, CITY_PAIRS
WHERE FLIGHTS.DEPARTURE_AIRPORT=CITY_PAIRS.DEPARTURE_AIRPORT
GROUP BY FLIGHT_ID
HAVING FLIGHTS.FLIGHT_NUMBER LIKE 'sky%';

SELECT AVG(CITY_PAIRS.DISTANCE)
FROM FLIGHTS, CITY_PAIRS
WHERE FLIGHTS.DEPARTURE_AIRPORT=CITY_PAIRS.DEPARTURE_AIRPORT
GROUP BY FLIGHT_ID
HAVING FLIGHTS.FLIGHT_NUMBER LIKE 'sky%';

SELECT SUM(CITY_PAIRS.DISTANCE), AVG(CITY_PAIRS.DISTANCE)
FROM FLIGHTS, CITY_PAIRS
WHERE FLIGHTS.DEPARTURE_AIRPORT=CITY_PAIRS.DEPARTURE_AIRPORT
AND FLIGHTS.FLIGHT_NUMBER LIKE 'sky%';


SELECT AVG(CITY_PAIRS.DISTANCE)
FROM FLIGHTS, CITY_PAIRS
WHERE FLIGHTS.DEPARTURE_AIRPORT=CITY_PAIRS.DEPARTURE_AIRPORT
AND FLIGHTS.FLIGHT_NUMBER LIKE 'sky%';


SELECT FLIGHTS.FLIGHT_NUMBER, CITY_PAIRS.DISTANCE, CITY_PAIRS.DEPARTURE_AIRPORT
FROM FLIGHTS, CITY_PAIRS
WHERE FLIGHTS.DEPARTURE_AIRPORT=CITY_PAIRS.DEPARTURE_AIRPORT
GROUP BY FLIGHTS.FLIGHT_NUMBER
HAVING FLIGHTS.FLIGHT_NUMBER LIKE 'sky%';

SELECT  FLIGHTS.FLIGHT_ID, FLIGHTS.FLIGHT_NUMBER, CITY_PAIRS.DISTANCE, CITY_PAIRS.DEPARTURE_AIRPORT
FROM FLIGHTS, CITY_PAIRS
WHERE FLIGHTS.DEPARTURE_AIRPORT=CITY_PAIRS.DEPARTURE_AIRPOR
HAVING FLIGHTS.FLIGHT_NUMBER LIKE 'sky%';

SELECT  FLIGHTS.FLIGHT_ID, FLIGHTS.FLIGHT_NUMBER, CITY_PAIRS.DEPARTURE_AIRPORT, CITY_PAIRS.ARRIVAL_AIRPORT, CITY_PAIRS.DISTANCE
FROM FLIGHTS, CITY_PAIRS
WHERE FLIGHTS.DEPARTURE_AIRPORT=CITY_PAIRS.DEPARTURE_AIRPORT
AND FLIGHTS.FLIGHT_NUMBER LIKE 'sky%';
4770 ROWS

SELECT FLIGHTS.FLIGHT_ID, FLIGHTS.FLIGHT_NUMBER, FLIGHTS.DEPARTURE_AIRPORT, FLIGHTS.ARRIVAL_AIRPORT, CITY_PAIRS.DISTANCE
FROM FLIGHTS, CITY_PAIRS
WHERE FLIGHTS.DEPARTURE_AIRPORT=CITY_PAIRS.DEPARTURE_AIRPORT
AND FLIGHTS.FLIGHT_NUMBER LIKE 'sky%';
1572 ROWS